server:
  port: ${PORT:5000}

logging:
  level:
    root: INFO

spring:
  # Настраиваем подключение к базе данных, если нет, то создаётся
  datasource:
   # url: jdbc:h2:~/Hexlet/java/exercises/migrations/h2db/hexlet # URL для запуска приложения из IDEA (временный)
    url: jdbc:h2:./hexlet   # URL для запуска приложения из консоли
   # url: jdbc:h2:mem:testdb # для поднятия базы в памяти
   # url: jdbc:postgresql://172.25.120.42:5432/hexlet_db
    username: sa # postgres #
    password: # postgres

  # Настраиваем инструмент Liquibase
  # Указываем путь к основному файлу миграции
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  # включаем логгирование SQL выражений при работе с данными, сгенерённых ORM
  jpa:
    show-sql: true
    # определяем, что ORM может делать с БД
    hibernate:
      ddl-auto: validate # проверка, что структура БД соответствует модели

  # Настраиваем консоль Н2
  # Это позволит нам открыть её в браузере по указанному пути: http://localhost:5000/h2console
  # порт используется тот же, что и у приложения, т.е. server.port и другим для консоли h2 его не сделать
  h2:
    console:
      enabled: true
      # Указываем путь, по которому будет открываться консоль
      path: /h2console/
      settings:
        web-allow-others: true
