server:
  port: ${PORT:5000}

logging:
  level:
    root: INFO
    org:
      hibernate:
        type:
          descriptor.sql.BasicBinder: TRACE # логирование значений параметров запроса

spring:
  datasource:
    url: jdbc:h2:./hexlet
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # to make the printing SQL beautify

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true

